name: Nuget Exporter
on: push
jobs:
  nugetpush:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./ 
    steps:
      - uses: actions/checkout@main
      - name: restore
        run: dotnet restore
      - name: build nuget
        run: dotnet pack -c Release
      - name: push PiKAEngine
        run: dotnet nuget push ./PiKAEngine/bin/Release/PiKAEngine.6.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: push PiKAEngine.DebugSystem
        run: dotnet nuget push ./PiKAEngine.DebugSystem/bin/Release/PiKAEngine.DebugSystem.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: push PiKAEngine.Entities
        run: dotnet nuget push ./PiKAEngine.Entities/bin/Release/PiKAEngine.Entities.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: push PiKAEngine.InventorySystem
        run: dotnet nuget push ./PiKAEngine.InventorySystem/bin/Release/PiKAEngine.InventorySystem.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: push PiKAEngine.MultiPlay.Client
        run: dotnet nuget push ./PiKAEngine.MultiPlay.Client/bin/Release/PiKAEngine.MultiPlay.Client.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: push PiKAEngine.MultiPlay.Server
        run: dotnet nuget push ./PiKAEngine.MultiPlay.Server/bin/Release/PiKAEngine.MultiPlay.Server.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
